// Generated by gencpp from file reactive_components/pauseRobot_ResetStateResult.msg
// DO NOT EDIT!


#ifndef REACTIVE_COMPONENTS_MESSAGE_PAUSEROBOT_RESETSTATERESULT_H
#define REACTIVE_COMPONENTS_MESSAGE_PAUSEROBOT_RESETSTATERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reactive_components
{
template <class ContainerAllocator>
struct pauseRobot_ResetStateResult_
{
  typedef pauseRobot_ResetStateResult_<ContainerAllocator> Type;

  pauseRobot_ResetStateResult_()
    : result_message()  {
    }
  pauseRobot_ResetStateResult_(const ContainerAllocator& _alloc)
    : result_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_message_type;
  _result_message_type result_message;





  typedef boost::shared_ptr< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> const> ConstPtr;

}; // struct pauseRobot_ResetStateResult_

typedef ::reactive_components::pauseRobot_ResetStateResult_<std::allocator<void> > pauseRobot_ResetStateResult;

typedef boost::shared_ptr< ::reactive_components::pauseRobot_ResetStateResult > pauseRobot_ResetStateResultPtr;
typedef boost::shared_ptr< ::reactive_components::pauseRobot_ResetStateResult const> pauseRobot_ResetStateResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator1> & lhs, const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_message == rhs.result_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator1> & lhs, const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reactive_components

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be8a5eb8699d93f379b287dcfc6e376c";
  }

  static const char* value(const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe8a5eb8699d93f3ULL;
  static const uint64_t static_value2 = 0x79b287dcfc6e376cULL;
};

template<class ContainerAllocator>
struct DataType< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reactive_components/pauseRobot_ResetStateResult";
  }

  static const char* value(const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"string result_message\n"
;
  }

  static const char* value(const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pauseRobot_ResetStateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reactive_components::pauseRobot_ResetStateResult_<ContainerAllocator>& v)
  {
    s << indent << "result_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REACTIVE_COMPONENTS_MESSAGE_PAUSEROBOT_RESETSTATERESULT_H
