// Generated by gencpp from file trajcetorie_generators/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TRAJCETORIE_GENERATORS_MESSAGE_ADDTWOINTS_H
#define TRAJCETORIE_GENERATORS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <trajcetorie_generators/AddTwoIntsRequest.h>
#include <trajcetorie_generators/AddTwoIntsResponse.h>


namespace trajcetorie_generators
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace trajcetorie_generators


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trajcetorie_generators::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::trajcetorie_generators::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::trajcetorie_generators::AddTwoInts > {
  static const char* value()
  {
    return "trajcetorie_generators/AddTwoInts";
  }

  static const char* value(const ::trajcetorie_generators::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::trajcetorie_generators::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::trajcetorie_generators::AddTwoInts >
template<>
struct MD5Sum< ::trajcetorie_generators::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trajcetorie_generators::AddTwoInts >::value();
  }
  static const char* value(const ::trajcetorie_generators::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajcetorie_generators::AddTwoIntsRequest> should match
// service_traits::DataType< ::trajcetorie_generators::AddTwoInts >
template<>
struct DataType< ::trajcetorie_generators::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::trajcetorie_generators::AddTwoInts >::value();
  }
  static const char* value(const ::trajcetorie_generators::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trajcetorie_generators::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::trajcetorie_generators::AddTwoInts >
template<>
struct MD5Sum< ::trajcetorie_generators::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trajcetorie_generators::AddTwoInts >::value();
  }
  static const char* value(const ::trajcetorie_generators::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajcetorie_generators::AddTwoIntsResponse> should match
// service_traits::DataType< ::trajcetorie_generators::AddTwoInts >
template<>
struct DataType< ::trajcetorie_generators::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::trajcetorie_generators::AddTwoInts >::value();
  }
  static const char* value(const ::trajcetorie_generators::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJCETORIE_GENERATORS_MESSAGE_ADDTWOINTS_H
