; Auto-generated. Do not edit!


(cl:in-package reactive_components-msg)


;//! \htmlinclude basic_first_interruptFeedback.msg.html

(cl:defclass <basic_first_interruptFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback_data
    :reader feedback_data
    :initarg :feedback_data
    :type cl:integer
    :initform 0))
)

(cl:defclass basic_first_interruptFeedback (<basic_first_interruptFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <basic_first_interruptFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'basic_first_interruptFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name reactive_components-msg:<basic_first_interruptFeedback> is deprecated: use reactive_components-msg:basic_first_interruptFeedback instead.")))

(cl:ensure-generic-function 'feedback_data-val :lambda-list '(m))
(cl:defmethod feedback_data-val ((m <basic_first_interruptFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader reactive_components-msg:feedback_data-val is deprecated.  Use reactive_components-msg:feedback_data instead.")
  (feedback_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <basic_first_interruptFeedback>) ostream)
  "Serializes a message object of type '<basic_first_interruptFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'feedback_data)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <basic_first_interruptFeedback>) istream)
  "Deserializes a message object of type '<basic_first_interruptFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback_data) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<basic_first_interruptFeedback>)))
  "Returns string type for a message object of type '<basic_first_interruptFeedback>"
  "reactive_components/basic_first_interruptFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'basic_first_interruptFeedback)))
  "Returns string type for a message object of type 'basic_first_interruptFeedback"
  "reactive_components/basic_first_interruptFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<basic_first_interruptFeedback>)))
  "Returns md5sum for a message object of type '<basic_first_interruptFeedback>"
  "8b330198f62ce536f636cd9f765bf359")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'basic_first_interruptFeedback)))
  "Returns md5sum for a message object of type 'basic_first_interruptFeedback"
  "8b330198f62ce536f636cd9f765bf359")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<basic_first_interruptFeedback>)))
  "Returns full string definition for message of type '<basic_first_interruptFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback~%int32 feedback_data~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'basic_first_interruptFeedback)))
  "Returns full string definition for message of type 'basic_first_interruptFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback~%int32 feedback_data~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <basic_first_interruptFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <basic_first_interruptFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'basic_first_interruptFeedback
    (cl:cons ':feedback_data (feedback_data msg))
))
