; Auto-generated. Do not edit!


(cl:in-package reactive_components-msg)


;//! \htmlinclude pauseRobot_ResetStateGoal.msg.html

(cl:defclass <pauseRobot_ResetStateGoal> (roslisp-msg-protocol:ros-message)
  ((some_goal_data
    :reader some_goal_data
    :initarg :some_goal_data
    :type cl:integer
    :initform 0))
)

(cl:defclass pauseRobot_ResetStateGoal (<pauseRobot_ResetStateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pauseRobot_ResetStateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pauseRobot_ResetStateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name reactive_components-msg:<pauseRobot_ResetStateGoal> is deprecated: use reactive_components-msg:pauseRobot_ResetStateGoal instead.")))

(cl:ensure-generic-function 'some_goal_data-val :lambda-list '(m))
(cl:defmethod some_goal_data-val ((m <pauseRobot_ResetStateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader reactive_components-msg:some_goal_data-val is deprecated.  Use reactive_components-msg:some_goal_data instead.")
  (some_goal_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pauseRobot_ResetStateGoal>) ostream)
  "Serializes a message object of type '<pauseRobot_ResetStateGoal>"
  (cl:let* ((signed (cl:slot-value msg 'some_goal_data)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pauseRobot_ResetStateGoal>) istream)
  "Deserializes a message object of type '<pauseRobot_ResetStateGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'some_goal_data) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pauseRobot_ResetStateGoal>)))
  "Returns string type for a message object of type '<pauseRobot_ResetStateGoal>"
  "reactive_components/pauseRobot_ResetStateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pauseRobot_ResetStateGoal)))
  "Returns string type for a message object of type 'pauseRobot_ResetStateGoal"
  "reactive_components/pauseRobot_ResetStateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pauseRobot_ResetStateGoal>)))
  "Returns md5sum for a message object of type '<pauseRobot_ResetStateGoal>"
  "a4d87b9c68384aa77b0a6c45bc0d83d8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pauseRobot_ResetStateGoal)))
  "Returns md5sum for a message object of type 'pauseRobot_ResetStateGoal"
  "a4d87b9c68384aa77b0a6c45bc0d83d8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pauseRobot_ResetStateGoal>)))
  "Returns full string definition for message of type '<pauseRobot_ResetStateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int32 some_goal_data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pauseRobot_ResetStateGoal)))
  "Returns full string definition for message of type 'pauseRobot_ResetStateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int32 some_goal_data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pauseRobot_ResetStateGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pauseRobot_ResetStateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'pauseRobot_ResetStateGoal
    (cl:cons ':some_goal_data (some_goal_data msg))
))
