// Auto-generated. Do not edit!

// (in-package reactive_components.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class basic_first_interruptFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.feedback_data = null;
    }
    else {
      if (initObj.hasOwnProperty('feedback_data')) {
        this.feedback_data = initObj.feedback_data
      }
      else {
        this.feedback_data = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type basic_first_interruptFeedback
    // Serialize message field [feedback_data]
    bufferOffset = _serializer.int32(obj.feedback_data, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type basic_first_interruptFeedback
    let len;
    let data = new basic_first_interruptFeedback(null);
    // Deserialize message field [feedback_data]
    data.feedback_data = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'reactive_components/basic_first_interruptFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8b330198f62ce536f636cd9f765bf359';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the feedback
    int32 feedback_data
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new basic_first_interruptFeedback(null);
    if (msg.feedback_data !== undefined) {
      resolved.feedback_data = msg.feedback_data;
    }
    else {
      resolved.feedback_data = 0
    }

    return resolved;
    }
};

module.exports = basic_first_interruptFeedback;
