// Auto-generated. Do not edit!

// (in-package reactive_components.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class pauseRobot_ResetStateGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.some_goal_data = null;
    }
    else {
      if (initObj.hasOwnProperty('some_goal_data')) {
        this.some_goal_data = initObj.some_goal_data
      }
      else {
        this.some_goal_data = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type pauseRobot_ResetStateGoal
    // Serialize message field [some_goal_data]
    bufferOffset = _serializer.int32(obj.some_goal_data, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type pauseRobot_ResetStateGoal
    let len;
    let data = new pauseRobot_ResetStateGoal(null);
    // Deserialize message field [some_goal_data]
    data.some_goal_data = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'reactive_components/pauseRobot_ResetStateGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a4d87b9c68384aa77b0a6c45bc0d83d8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    int32 some_goal_data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new pauseRobot_ResetStateGoal(null);
    if (msg.some_goal_data !== undefined) {
      resolved.some_goal_data = msg.some_goal_data;
    }
    else {
      resolved.some_goal_data = 0
    }

    return resolved;
    }
};

module.exports = pauseRobot_ResetStateGoal;
